import Foundation
import HealthKit

/// Determines whether the current user has an Apple Watch paired and syncing data.
///
/// HealthKit has no direct "has Apple Watch" API. We use two heuristics:
/// 1. Query `appleStandHour` samples — only generated by Apple Watch.
/// 2. Check `HKActivitySummary.appleExerciseTimeGoal` source is Apple Watch.
actor WatchDetector {

    private let store: HKHealthStore

    init(store: HKHealthStore = HealthKitManager.shared.store) {
        self.store = store
    }

    /// Returns true if Apple Watch data is present within the past 7 days.
    func detectAppleWatch() async -> Bool {
        await withCheckedContinuation { continuation in
            let sevenDaysAgo = Date().addingTimeInterval(-7 * 24 * 3600)
            let predicate = HKQuery.predicateForSamples(withStart: sevenDaysAgo, end: Date())
            let sortDescriptor = NSSortDescriptor(key: HKSampleSortIdentifierEndDate, ascending: false)

            let query = HKSampleQuery(
                sampleType: HKCategoryType(.appleStandHour),
                predicate: predicate,
                limit: 1,
                sortDescriptors: [sortDescriptor]
            ) { _, samples, _ in
                guard let samples, !samples.isEmpty else {
                    continuation.resume(returning: false)
                    return
                }
                // Verify the source is Apple Watch (not manually entered).
                let fromWatch = samples.contains {
                    $0.sourceRevision.source.bundleIdentifier.contains("com.apple.health") &&
                    $0.sourceRevision.productType?.lowercased().contains("watch") == true
                }
                continuation.resume(returning: fromWatch)
            }
            store.execute(query)
        }
    }
}
